---
paths:
    code_core: ""  # has to be an absolute path to external code base
    base_path: Dropbox/Icke/Work/DigiWest  # abs or relative to home
    # all paths belowe are absolute paths or relative to base_path
    data_path: data
    output_path: output
    info_path: info
    img_path: output/img
    tables_path: output/tables
extract_data:  # here are the configs for the "load_and_save function"
    remove_zz: True
    read_lines: 0
    excel_sheet: RawData
    format_analytes: True
normscale:
    sample_cols: 
        - Pop
        - Stim
        - Cyto
    analyte_cols:
        - Analyte
        - Phospho
        - Peak
    norm2control:  # give the
        data_cols:
            - medMFI_sc
            - logMFI_sc
        norms:
            - Cyto: wo
            - Cyto: CXCL10
            - Cyto: CXCL9
        operations:
            - min
plot_heatmap:
    figsize: [7,7]
    plot_type: png
    max_NA: 0.9
    data_col: logMFI_sc_minWO
    main: Digiwest heatmap
    heat_color: heat  # magma
    fontsize_row: 10
    cluster_cols: True
    cluster_rows: True
    cutree_rows: 3
    cutree_cols: 3
    treeheight_row: 17
    treeheight_col: 17
    show_colnames: False
    row_info:
        - Peak
        - Phospho
    show_phospho_only: True
    show_extra_peak: False
    col_info:
        - Cyto
        - Pop
        - Stim
    show_cytos: # make new exclude list
        - IL-2
        - wo
        - CXCL9
        - CXCL10
        - CXCL11
    show_stims:
        - unstim
        - stim
